"""initial

Revision ID: bc3c61b62789
Revises: 
Create Date: 2026-03-16 11:00:44.341358
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc3c61b62789'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('anonymized_summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('share_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shamir_k', sa.Integer(), nullable=False),
    sa.Column('shamir_n', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('technical_domain', sa.String(length=100), nullable=True),
    sa.Column('novelty_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prior_art_known', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('potential_applications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('development_stage', sa.String(length=30), nullable=True),
    sa.Column('self_assessed_value', sa.Float(), nullable=True),
    sa.Column('outside_option_value', sa.Float(), nullable=True),
    sa.Column('confidential_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_disclosure_fraction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invention_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('alpha_0', sa.Float(), nullable=True),
    sa.Column('budget_cap', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('security_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seller_confirmed', sa.Boolean(), nullable=False),
    sa.Column('buyer_confirmed', sa.Boolean(), nullable=False),
    sa.Column('enclave_id', sa.String(length=255), nullable=True),
    sa.Column('attestation_doc', sa.LargeBinary(), nullable=True),
    sa.Column('negotiation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invention_id'], ['inventions.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreement_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('omega_hat', sa.Float(), nullable=True),
    sa.Column('negotiation_rounds', sa.Integer(), nullable=True),
    sa.Column('encrypted_transcript', sa.LargeBinary(), nullable=True),
    sa.Column('transcript_key_ref', sa.String(length=255), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('payee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mock_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('audit_log')
    op.drop_table('agreement_outcomes')
    op.drop_table('agreements')
    op.drop_table('inventions')
    op.drop_table('users')
    # ### end Alembic commands ###
