"""LLM-powered policy generator — Conseca pattern.

Generates context-specific PolicyConstraints via LLM, then merges with
hardcoded defaults as a baseline. Falls back to defaults on LLM failure
(fail-secure).
"""

import json
import logging
from typing import Any

from ndai.enclave.agents.sanitize import escape_for_prompt
from ndai.enclave.policy.engine import Policy, PolicyConstraint

logger = logging.getLogger(__name__)


# ── Default policies (always applied as baseline) ──

DEFAULT_RECALL_CONSTRAINTS = [
    PolicyConstraint(
        field="result",
        deny_patterns=[r"https?://\S+", r"[A-Za-z0-9+/]{100,}={0,2}"],
        max_length=2000,
        rationale="No URLs or long base64 strings in recall results",
    ),
]

DEFAULT_PROPS_CONSTRAINTS = [
    PolicyConstraint(
        field="executive_summary",
        max_length=500,
        deny_patterns=[r"https?://\S+"],
        rationale="Summary must be concise, no URLs",
    ),
    PolicyConstraint(
        field="sentiment",
        pattern=r"(positive|neutral|negative)",
        rationale="Sentiment must be one of the allowed enum values",
    ),
]


def _default_policy(task_type: str) -> Policy:
    """Return the hardcoded default policy for a task type."""
    if task_type == "recall":
        return Policy(
            task_type="recall",
            constraints=list(DEFAULT_RECALL_CONSTRAINTS),
            context_summary="default recall policy",
        )
    elif task_type == "props":
        return Policy(
            task_type="props",
            constraints=list(DEFAULT_PROPS_CONSTRAINTS),
            context_summary="default props policy",
        )
    else:
        return Policy(task_type=task_type, constraints=[], context_summary="unknown task type")


_GENERATOR_PROMPT = """\
You are a security policy generator for a Trusted Execution Environment.
Given the task type and context, generate specific constraints for validating LLM output.

Return ONLY valid JSON — an array of constraint objects:
[
  {{
    "field": "field_name",
    "pattern": "optional regex the value must match (fullmatch)",
    "deny_patterns": ["regex patterns the value must NOT contain"],
    "max_length": 1000,
    "rationale": "why this constraint exists"
  }}
]

Task type: {task_type}
Context: {context}

Generate constraints that are specific to this context. Be conservative — deny anything suspicious.
"""


def _parse_llm_constraints(raw: str) -> list[PolicyConstraint]:
    """Parse LLM response into PolicyConstraint objects."""
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[1] if "\n" in cleaned else cleaned[3:]
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3]
    cleaned = cleaned.strip()

    data = json.loads(cleaned)
    if not isinstance(data, list):
        raise ValueError("Expected JSON array")

    constraints = []
    for item in data:
        constraints.append(PolicyConstraint(
            field=item.get("field", "unknown"),
            pattern=item.get("pattern"),
            deny_patterns=item.get("deny_patterns", []),
            max_length=item.get("max_length"),
            rationale=item.get("rationale", ""),
        ))
    return constraints


def _merge_constraints(
    defaults: list[PolicyConstraint],
    generated: list[PolicyConstraint],
) -> list[PolicyConstraint]:
    """Merge generated constraints with defaults. Defaults always included."""
    # Index generated by field name
    gen_by_field = {c.field: c for c in generated}
    merged = list(defaults)  # defaults always first

    for field_name, gen_c in gen_by_field.items():
        # Only add generated constraints for fields not already covered by defaults
        if not any(d.field == field_name for d in defaults):
            merged.append(gen_c)

    return merged


def generate_policy(
    task_type: str,
    context: str,
    llm_client: Any,
) -> Policy:
    """Generate a context-specific policy using LLM, merged with defaults.

    Falls back to defaults only if LLM fails (fail-secure).

    Args:
        task_type: 'recall' or 'props'.
        context: Description of what the user is trying to do.
        llm_client: Any LLM client with create_message() + extract_text().

    Returns:
        Policy with merged constraints.
    """
    default = _default_policy(task_type)

    try:
        safe_context = escape_for_prompt(context)
        prompt = _GENERATOR_PROMPT.format(task_type=task_type, context=safe_context)

        response = llm_client.create_message(
            system="You are a security policy generator. Return only valid JSON.",
            messages=[{"role": "user", "content": prompt}],
        )
        raw = llm_client.extract_text(response)
        generated = _parse_llm_constraints(raw)

        merged = _merge_constraints(default.constraints, generated)
        return Policy(
            task_type=task_type,
            constraints=merged,
            context_summary=f"LLM-generated for: {context[:100]}",
        )
    except Exception as e:
        logger.warning("Policy generation failed, using defaults: %s", e)
        return default
